[package]
name = "euclidean_distance"
version = "0.1.0"
authors = ["Peshala Prabhapoorna <peshalaprabhapoorna@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
